### ISSUE TITLE
LSP Stop Working When Typing `()`

### ISSUE THREAD

**Issue by rennsax** [Shopify/vscode-ruby-lsp#1021]
### Operating System

MacOS

### Ruby version

3.3.0

### Project has a bundle

- [X] Has bundle

### Ruby version manager being used

rbenv

### Description

When I try to type a simple expression:

```
(1..5).each { |num| puts num }
```

As the parenthesis is type, the LSP is stuck (no future linting available).

I try to restart the LSP and it didn't work. After reloading the VSCode window it restores.

But the process Ruby-LSP is left on the background and occupies a lot of CPU:

![Screenshot 2024-02-03 at 15 22 48](https://github.com/Shopify/vscode-ruby-lsp/assets/93167100/4efe0603-ebdb-4054-93f1-adf168737f99)

How can it happen?

**Comment by vinistock** [comment]
Thank you for the bug report!

We need to identify what exactly is causing this. Can you reproduce this consistently? If so, you might be able to identify which LSP request causes this by enabling server tracing.

```jsonc
{
  // Put this in your user settings to see server tracing
  "ruby lsp.trace.server": "messages"
}
```
Then check the `Ruby LSP` channel in VS Code's `Output` tab. When you reproduce the problem, is there a specific request that takes longer or causes it to hang?

**Comment by vinistock** [comment]
Indeed, it looks like the LSP server crashed for some reason. Do you see a point in the logs where the editor stops receiving responses?

While the LSP is working, you should be able to see the responses coming back. If you have the exact point in the logs where you stop seeing them, that would be helpful.

**Comment by rennsax** [comment]
The log I reported is exactly the point. Before that, a response is received.

**Comment by vinistock** [comment]
What was the last request for which you received a response? The one before `signatureHelp`?

**Comment by rennsax** [comment]
Today I found the bug may be fixed. Closed now.
