### ISSUE TITLE
CPU eater

### ISSUE THREAD

**Issue by slayer** [Shopify/vscode-ruby-lsp#1037]
### Operating System

MacOS

### Ruby version

3.2.2

### Project has a bundle

- [X] Has bundle

### Ruby version manager being used

rbenv

### Description

Eats all CPU on M2 Pro

**Comment by andyw8** [comment]
It's very difficult to help you with such little information provided.

To begin, which version of the Ruby LSP gem is in use?

**Comment by andyw8** [comment]
I will close this since the original author did not respond.

@davidcelis can you please create a separate issue for that.
