### ISSUE TITLE
Add vscode-ruby-lsp to the List of VSCode Debug Adaptors

### ISSUE THREAD

**Issue by mslinn** [Shopify/vscode-ruby-lsp#1039]
The [list](https://microsoft.github.io/debug-adapter-protocol//implementors/adapters/) mentions Rebornix, but not vscode-ruby-lsp

**Comment by andyw8** [comment]
(will update after monorepo merge)

**Comment by andyw8** [comment]
Completed in https://github.com/microsoft/debug-adapter-protocol/pull/471
