### ISSUE TITLE
Create a status bar button for centralized Ruby LSP interaction

### ISSUE THREAD

**Issue by vinistock** [Shopify/vscode-ruby-lsp#262]
We initially attempted to tell users about best practices and how to set up the Ruby LSP through `showInformation` dialogues. However, this does not seem to achieve the goal as we expected and we actually end up causing notification fatigue on developers.

It would be nice to unify all interaction with the Ruby LSP through a status bar button.

### Idea

The status bar item could
- Display the current status of the Ruby LSP server (ready, stopped, errored or not installed)
- Clicking on it would then open a `showInformation` dialogue with action options depending on the state
    - if the server is running, then show stop or restart
    - if the server gem is not in the bundle, then show bundle add
    - if the server has errored, then show a reload window button
    - if the server is stopped, then show a start button

### Note

The only interaction I believe should continue to be a notification is if the gems are not installed (bundle install prompt).

**Comment by adisonlampert** [comment]
In addition to the features above, the status button will now include:
- The Ruby version
- Whether it’s using YJIT or not
- If the server gem is outdated

We are now implementing with the VS Code recommended [language status item](https://code.visualstudio.com/api/references/vscode-api#LanguageStatusItem).

**Comment by joeyschoblaska** [comment]
Will these syntax error notifications be going away as well? I timed it and they stick around for _20 seconds_, whether you fix the error or not.

<img width="485" alt="image" src="https://user-images.githubusercontent.com/29129/215924943-6df5230a-a07f-46a8-88ad-ae0e111f232d.png">

**Comment by vinistock** [comment]
The centralized place for interactions would be for displaying current information (e.g.: server is stopped, server has errored) and buttons to perform actions on it.

That specific warning is an error coming trying to execute the formatting request. There's no way to automatically dismiss it from the server or change how long they stick around, as far as I know.

Are you using the Ruby LSP with RuboCop? If so, you should see diagnostics ahead of time so that you can fix the syntax before trying to save the file.
