### ISSUE TITLE
After some usage I see several LSP instances running

### ISSUE THREAD

**Issue by megatux** [Shopify/vscode-ruby-lsp#348]
>$ ps ax|grep ruby-lsp      
44141   ??  S      0:07.40 /Users/megatux/.asdf/installs/ruby/2.7.6/bin/ruby-lsp   
46489   ??  S      0:06.44 /Users/megatux/.asdf/installs/ruby/2.7.6/bin/ruby-lsp   
46610   ??  S      0:06.34 /Users/megatux/.asdf/installs/ruby/2.7.6/bin/ruby-lsp   
46684   ??  S      0:06.33 /Users/megatux/.asdf/installs/ruby/2.7.6/bin/ruby-lsp   

<img width="626" alt="Captura de pantalla 2023-01-11 a la(s) 14 32 44" src="https://user-images.githubusercontent.com/850020/211877890-355a83f4-95d1-4c94-aca0-b0442cf177f4.png">

**Comment by vinistock** [comment]
Can you provide more details? What are the steps you need to take to end up in this scenario? Are you on the latest version of the `ruby-lsp` gem?

**Comment by megatux** [comment]
Version `ruby-lsp (0.3.7)`. 
I think the easiest steps to reproduce it are, 
- having the Gemfile with the ruby-lsp gem added but not commited
- from terminal: git staging
- moving back to vscode (it will prompt to install the ruby-lsp gem)
<img width="693" alt="Captura de pantalla 2023-01-11 a la(s) 15 00 31" src="https://user-images.githubusercontent.com/850020/211883882-430cf247-a39a-45bb-92a0-b12a5c5da48e.png">
- do not install it
- going to terminal again and `git stash pop` so the Gemfile is restored w/ruby-lsp gem
- going back to vscode and clicking on [Run bundle install]

this creates a new ruby-lsp process here.

Env: Macbook M1, Ventura. brew + asdf for version manager.

**Comment by vinistock** [comment]
If you have a chance, can you please try the latest v0.0.13 release and check it the issue is fixed?

**Comment by megatux** [comment]
Great! thanks, updated the extension to that version. Will report any issue I found. Regards
