### ISSUE TITLE
Ruby LSP it cannot format "Ruby" Files

### ISSUE THREAD

**Issue by JohnAnon9771** [Shopify/vscode-ruby-lsp#370]
I just updated ruby lsp from vscode to 0.0.13 and now it's getting this error when trying to format.

<img width="1372" alt="image" src="https://user-images.githubusercontent.com/42195321/216634148-54ea63d2-98f8-429e-8eb5-0cf176427173.png">

**Comment by JohnAnon9771** [comment]
I use `asdf` as my version manager.

**Comment by vinistock** [comment]
What do you mean by local version? Since the Ruby LSP must be a part of the bundle, then `asdf` needs to activate whatever version is used by the current project you're working on.

**Comment by JohnAnon9771** [comment]
> What do you mean by local version? Since the Ruby LSP must be a part of the bundle, then `asdf` needs to activate whatever version is used by the current project you're working on.

Projects that use `asdf` have a file called .tool-versions where they define the local version (dir) I'm using from ruby, but it seems ruby-lsp looks at the global .tool-versions that exists in my home dir... 

In the following prints I will always be showing my .tool-versions of my project where my local ruby is defined, which will always be`2.7.7` (because my project needs that version). However in the corner of my vscode ruby-lsp always shows the versions that are in my global .tool-versions...

With global `3.2.0`

<img width="1372" alt="image" src="https://user-images.githubusercontent.com/42195321/216661917-1a337586-9f0d-4a9e-adf8-f728487e839d.png">

With global `2.7.7`

<img width="1372" alt="image" src="https://user-images.githubusercontent.com/42195321/216662074-6d35c524-e575-48e8-a050-07e0801338f3.png">

**Comment by vinistock** [comment]
Was this not a problem before `v0.0.13`? It's probably related to this PR then https://github.com/Shopify/vscode-ruby-lsp/pull/349.

Not sure why using the interactive shell wouldn't activate the project Ruby version in `asdf` though.

**Comment by andyw8** [comment]
Hi, @JohnAnon9771. I use `asdf` but I'm having trouble reproducing this. The following would be helpful to know:

* Do you have `"rubyLsp.rubyVersionManager": "asdf"` in your settings?
* Does switching back to v0.0.12 solve the problem? (you can right click on the extension and choose `Install Another Version`.
* If you have a `~/.asdfrc` file, what are its contents?
* Does the problem still occur if you start VS Code from inside the project directory with `code .`?
* Do you have any other Ruby version managers installed, e.g. rvm?
