### ISSUE TITLE
Not sure what this warning it, but it is consistent

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/vscode-ruby-lsp#372]
I use Standard. In my bundles I added ruby-lsp. I have this VSCode ruby-lsp added to my VSCode. 

I still get that little nag dialog about not having ruby-lsp in the bundle, and asking to bundle install it. 

What is up with that? I get it, complex stuff. But it makes using this language server, suspect? Not sure it matters. But I am curious as to what causes this, and perhaps what the workaround is to get that to not happen.

**Comment by vinistock** [comment]
Typically, if you have bundle installed already and the extension keeps showing you that it needs to bundle install it means that it is selecting the wrong version of Ruby.

Do you use any version managers (e.g.: `chruby`, `asdf`)? And if so, did you already configure the extension to use your preferred manager ([docs](https://github.com/Shopify/vscode-ruby-lsp#configuration))?

I should also mention that the Ruby LSP doesn't support `Standard` yet. So, you can get it to work, but the code can only be formatted with RuboCop or Syntax Tree at this time.

**Comment by vinistock** [comment]
Adding `"rubyLsp.rubyVersionManager": "rbenv"` to your VS Code configurations should select the correct version manager, which should make the bundle install dialogues go away.

While we don't yet support Standard as a formatter, you can still use the Ruby LSP with formatting disabled if you want. Just configure your enabled features to pick the ones you want.
```jsonc
"rubyLsp.enabledFeatures": {
  "formatting": false
  // keep everything else enabled
}
```

**Comment by resistorsoftware** [comment]
Thank you! Will try all this out and see how it goes.

**Comment by resistorsoftware** [comment]
I actually did have the correct setting, yet that prompt to install the bundle continues.. this is why I quit VSCode before, it just cannot handle the fact I have projects open that each have their own version of Ruby running... hence with it's global configuration it has all sorts of per project issues.

<img width="386" alt="image" src="https://user-images.githubusercontent.com/123307/217020374-4e7702cc-a785-45cd-8577-22102d544584.png">

**Comment by vinistock** [comment]
Do you have multiple projects open in the same instance of VS Code? If that's the case, indeed the Ruby LSP doesn't support that well yet.

**Comment by resistorsoftware** [comment]
Absolutely! I see no reason not to work that way. But I do understand, VSCode is probably under-whelming for this use case. I keep hearing how RubyMine is actually the only editor that truly works at a pro-level... but I have never tried it with any gusto. Maybe I should!
