### ISSUE TITLE
Failed to activate rbenv environment: Unexpected token F in JSON at position 0

### ISSUE THREAD

**Issue by gopeter** [Shopify/vscode-ruby-lsp#380]
I'm using VSCode Ruby LSP v.0.0.13, `ruby-lsp` 0.3.8 and `rbenv` and get this error message when I open VSCode:

Failed to activate rbenv environment: Unexpected token F in JSON at position 0

I have no clue how I can help to debug this. I tried to get some information in VSCode's developer console, but didn't found anything helpful.

**Update**

I've also checked if `rbenv` is available in VSCode's terminal (which is the case):
```
rbenv -v
rbenv 1.2.0
```

**Update 2** 

This doesn't happen with plugin version 0.0.12

**Comment by olivier-thatch** [comment]
I'm running into a similar issue, except that the error message indicates that JSON parsing fails on a whitespace character (or possibly no character?):
```
Failed to activate rbenv environment: Unexpected token  in JSON at position 0
```

I've tried manually running the same command that the extension itself runs:
```sh
$ /bin/zsh -lic 'rbenv exec ruby -rjson -e "puts JSON.dump(ENV.to_h)"'
{"RBENV_VERSION":"3.2.0",...}
```

I suspect #349 broke something as I don't think this was happening with 0.0.12.

**Comment by gopeter** [comment]
For sure:

```
$ ruby -e "p \`/bin/zsh -lic 'whoami'\`"
"peter_oesteritz\n"
```

**Comment by olivier-thatch** [comment]
Weird, that doesn't seem to include any extra characters 🤔 

@gopeter Can you try running this command from the same directory that you're opening as the VSCode project where you're seeing the Ruby LSP error (to make sure it's using the same `.ruby-version` and environment):
```sh
$ rbenv exec ruby -e "p \`#{ENV['SHELL']} -lic 'rbenv exec ruby -rjson -e \"puts JSON.dump(ENV.to_h)\"'\`"
```

**Comment by olivier-thatch** [comment]
Oh, clever! Just updated and I no longer get the error.

**Comment by gopeter** [comment]
It's also working fine for me 👍
