### ISSUE TITLE
Move `.ruby-lsp` folder logic into the server

### ISSUE THREAD

**Issue by vinistock** [Shopify/vscode-ruby-lsp#421]
Based on https://github.com/Shopify/vscode-ruby-lsp/pull/419#discussion_r1120876546.

To make the Ruby LSP work similarly on every editor, we should move the `.ruby-lsp` logic into the server. This might require us to create another executable that basically just sets up the folder, sets up bundle and then just runs `bundle exec ruby-lsp` at the end.

**Comment by paracycle** [comment]
Just want to note that this does not need a separate executable. The `ruby-lsp` executable can do the appropriate set up if `BUNDLE_GEMFILE` env variable is not set or is empty. After setup, it can replace itself with `BUNDLE_GEMFILE` env variable through the [`Kernel#exec` call](https://ruby-doc.org/3.2.0/Kernel.html#method-i-exec). The behaviour of the same `ruby-lsp` executable when `BUNDLE_GEMFILE` env variable is set would be the current behaviour.

**Comment by vinistock** [comment]
In that case, what would be the execution from the extension? What I'm thinking is, if we run `bundle exec ruby-lsp` (without `BUNDLE_GEMFILE`), then it will fail because the `ruby-lsp` will not be a part of the project's bundle (which is what we want).

So in my head, the way around it would be to `gem install ruby-lsp`, run some other executable globally like `ruby-lsp-boot`, which would then set up the custom `Gemfile` and run `bundle exec ruby-lsp`.
