### ISSUE TITLE
Problem running extension in devcontainer.

### ISSUE THREAD

**Issue by zewelor** [Shopify/vscode-ruby-lsp#488]
Hi

I'm using devcontainer, with Ruby LSP extension version 0.2.2. When starting I get following error:

```Failed to activate none environment: Command failed: ruby --disable-gems -e 'puts "#{RUBY_VERSION},#{defined?(RubyVM::YJIT)}"' /bin/sh: ruby: not found```

![Screenshot_20230327_141555](https://user-images.githubusercontent.com/389828/227939209-59c75e3e-02a8-447f-a1c8-a714cba02d46.png)

When I run new terminal window, inside container via devcontainer, I can execute this command without problem:
```
/app $ which ruby
/usr/local/bin/ruby
/app $ ruby --disable-gems -e 'puts "#{RUBY_VERSION},#{defined?(RubyVM::YJIT)}"'
3.1.3,constant
```

How can i debug it further ?

**Comment by vinistock** [comment]
I think the official [Remote extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh) could potentially be what you're looking for. My understanding is that it allows connecting to a remote machine / devcontainer and then VS Code just works as if it were running inside the remote machine.

**Comment by zewelor** [comment]
From what I understand this remote extension works for ssh only. I've tested latest version 0.2.4 and now I've got one less error. I assume work around ruby activation when none package manager is chosen fixed this. Now I have the same error as here: https://github.com/Shopify/vscode-ruby-lsp/issues/536 . So I'm closing this hoping fixing linked issue will make everything working in my case also.
