### ISSUE TITLE
Failed to activate rbenv environment

### ISSUE THREAD

**Issue by kadru** [Shopify/vscode-ruby-lsp#505]
Hi, I just trying to use this extension but it fails to activate:

```
Failed to activate rbenv environment: Command failed: /bin/bash -lic 'rbenv exec ruby --disable-gems -rjson -e "printf(%{RUBY_ENV_ACTIVATE%sRUBY_ENV_ACTIVATE}, JSON.dump(ENV.to_h))"' bash: no se puede establecer el grupo de proceso de terminal (11835): Función ioctl no apropiada para el dispositivo bash: no hay control de trabajos en este intérprete de ordenes No se ha encontrado la orden «rbenv», pero se puede instalar con: sudo apt install rbenv
```
It seems the extension cannot find `rbenv` but I can run the command that the extension is trying to run and is running without errors inside the vscode terminal.

I'm using:
 vscode 1.76.2
 ruby lsp extension 0.2.3
 ruby 2.7.7
 rbenv 1.1.2-40-g62d7798
 ubuntu 20.04

**Comment by vinistock** [comment]
Hey. Is `rbenv` loaded in your `~/.bashrc`?

**Comment by kadru** [comment]
Yes, is loaded with `eval "$(rbenv init -)"`

**Comment by vinistock** [comment]
Do you have another configuration file such as `~/.profile`? If you do, can you try activating `rbenv` there? I want to understand if maybe the interactive bash mode is not loading `~/.bashrc` by default.

**Comment by vinistock** [comment]
I thought using the `-i` flag for an interactive bash shell would load `~/.bashrc`. Is there a way to tell bash to load it?

**Comment by wwahammy** [comment]
I can't help on whether there's a better way to tell bash to load `~/.bashrc` though, this is not my area of expertise :smile:
