### ISSUE TITLE
Failed to activate rbenv environment

### ISSUE THREAD

**Issue by mamccr** [Shopify/vscode-ruby-lsp#518]
Whenever things start, I get the following error message from the extension:

```
Failed to activate rbenv environment: Command failed: /bin/zsh -lic 'rbenv exec ruby --disable-gems -rjson -e "printf(%{RUBY_ENV_ACTIVATE%sRUBY_ENV_ACTIVATE}, JSON.dump(ENV.to_h))"' /Users/markmccraw/.rbenv/versions/2.7.7/lib/ruby/2.7.0/json/common.rb:224:in `generate': "\\xE2" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError) from /Users/markmccraw/.rbenv/versions/2.7.7/lib/ruby/2.7.0/json/common.rb:224:in `generate' from /Users/markmccraw/.rbenv/versions/2.7.7/lib/ruby/2.7.0/json/common.rb:394:in `dump' from -e:1:in `<main>'
```

It's weird, because if I just pop open a terminal and run the thing it says failed, it runs fine. Not sure where else to look.

**Comment by vinistock** [comment]
It seems to be complaining about the encoding. Is your shell configured to use ASCII-8BIT? If it is, can you try changing to UTF-8 to see if that works?

If we identify that if fixes it, I wonder if we can force the encoding to be UTF-8 when running this command.

**Comment by mamccr** [comment]
That did it! Thanks @vinistock !
