### ISSUE TITLE
Ruby not found error with no version manager

### ISSUE THREAD

**Issue by Shankar1598** [Shopify/vscode-ruby-lsp#521]
Hi, the LSP extension is failing to start with the following error:

```
Failed to activate none environment: Command failed: ruby --disable-gems -e 'puts "#{RUBY_VERSION},#{defined?(RubyVM::YJIT)}"'
/bin/sh: 1: ruby: not found
```

When I run this command in terminal, am getting the following output:
```
3.2.2,
```

Am not using any version manager, I have tried setting version manager to both "none" and "auto"
```
➜  ~ which ruby
/snap/bin/ruby
➜  ~ ruby -v
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]
```

Any idea why it is failing? Thank you.

**Comment by andyw8** [comment]
Hi @Shankar1598, which shell do you use? (e.g. `zsh`).

**Comment by isaiahfrantz** [comment]
I have the same issue, using bash on fedora 37.
I do puppet development so I always use the ruby that comes packaged with the puppet agent to ensure compatibility with production.
ruby, gem, and bundle are in the path, in the vscode terminal I get:
>
> ❯ ruby --disable-gems -e 'puts "#{RUBY_VERSION},#{defined?(RubyVM::YJIT)}"'
> 2.5.9,
>

**Comment by rokit** [comment]
I have the same issue on Windows 10. I installed via the [ruby installer](https://rubyinstaller.org/downloads/). Ruby was automatically added to the path as `C:\Ruby31-x64\bin`. The `ruby --version` command works in both cmd and powershell, however this is the error when I load a ruby project in vscode:

```
Failed to activate none environment: Command failed: 'ruby --disable-gems -rjson -e "printf(%{RUBY_ENV_ACTIVATE%sRUBY_ENV_ACTIVATE}, JSON.dump(ENV.to_h))"' ''ruby' is not recognized as an internal or external command, operable program or batch file.
```
