### ISSUE TITLE
High CPU utilization when enabled

### ISSUE THREAD

**Issue by blackduckpartners** [Shopify/vscode-ruby-lsp#538]
I recently installed this extension after being prompted by VS Code to do so. Now, when opening VS Code, the Ubuntu 18.04 WSL2 instance that I'm connecting to has a persistent spike in CPU utilization. Opening HTOP in that WSL instance shows that the `/bin/bash -lic chruby --version` command is using one entire CPU core.

If I kill that process, the `/bin/bash -lic rbenv --version` command does the same thing and occupies one entire CPU core. Killing that starts `/bin/bash -lic rvm --version` using an entire core. Killing that command finally stops the cycle and everything seems to quite back down.

I do not have RBENV, RVM, or chruby installed on this instance and waiting any amount of time does not resolve the issue.

**Comment by vinistock** [comment]
I don't understand how this is happening. Is running `chruby --version` hanging? It should just print the version or fail if the tool is not installed.

If you run the command yourself on the terminal, do they also hang?

**Comment by blackduckpartners** [comment]
Yes, I agree. It does fail as expected when I run the command at the prompt, but still hangs when initiated by the extension. I've attached some screenshots here to help.

![Screenshot 2023-04-05 143459](https://user-images.githubusercontent.com/49367236/230199540-86a62cda-9396-40cb-a400-c372de5ac89a.png)

![Screenshot 2023-04-05 143556](https://user-images.githubusercontent.com/49367236/230199590-631228be-9b56-48cd-9429-a18fab9cf51a.png)

![Screenshot 2023-04-05 143619](https://user-images.githubusercontent.com/49367236/230199629-543a55da-79f2-4338-8093-2040eeda86f6.png)

![Screenshot 2023-04-05 143638](https://user-images.githubusercontent.com/49367236/230199658-185ae5a4-e318-4a5e-904e-0a80555bbf1d.png)

**Comment by blackduckpartners** [comment]
I'm seeing the same issues in `v0.2.4`. Additionally, I'm now seeing the same high usage for the `/bin/bash -ic ruby --disable-gems -rjson -e "printf(%{RUBY_ENV_ACTIVATE%sRUBY_ENV_ACTIVATE}, JSON.dump(ENV.to_h))"` command after killing the `chruby` `rbenv`, and `rvm` processes where i hadn't before.

**Comment by m3c-ode** [comment]
Hi there,

I would like to follow up on this matter, as the exact same thing happened to me. If I install this package, my VSCode and CPU go crazy (heats up to 90 degrees C). If this package is installed and VScode is running, it affects my laptop. It happened yesterday.
How can it be fixed on my machine?

**Comment by m3c-ode** [comment]
> It the `Ruby LSP` channel didn't show up, then we never got to the point of [instantiating the client](https://github.com/Shopify/vscode-ruby-lsp/blob/d7cb6f1a0256d0bd4dcdd7e42aae4589da16b1a7/src/extension.ts#L28).
> 
> We need to understand exactly where the extension is getting stuck. If you're willing to debug it, I think following these steps will help diagnose:
> 
> * Clone this repo
> * Make sure dependencies are installed (`yarn install`)
> * Put a breakpoint at the [first line in the extension activation](https://github.com/Shopify/vscode-ruby-lsp/blob/d7cb6f1a0256d0bd4dcdd7e42aae4589da16b1a7/src/extension.ts#L15)
> * Click F5 to run the extension in development mode. Make sure that the other VS Code window that gets opened has your Ruby project in it
> * Then keep stepping to try to figure out where exactly the extension is getting stuck

So I tried. 
Hitting F5 to run the debugger from the `extension.ts` file does open a new VScode window, but no folders are open. No ruby project. And I am unable to step in any further.

![image](https://github.com/Shopify/vscode-ruby-lsp/assets/99902649/75b72d69-ac8b-4619-bc67-ed89cd1cb557)

**Comment by m3c-ode** [comment]
In RubyLSP I defined it to use `rvm`as Ruby Version Manager. 
When I open a new VScode window, it still tries to run this process:

![image](https://github.com/Shopify/vscode-ruby-lsp/assets/99902649/7fc4a027-84f7-4842-bcec-c3059ebbfdd5)

Which I kill, then I get this notification in the VScode window.

**Comment by andyw8** [comment]
Sorry, ignore the above.

**Comment by vinistock** [comment]
It seems that all of the processes that keep hanging are the ones trying to run shell commands to activate the Ruby version. I'm not sure why they're hanging though.

Does running this manually also hang?

```shell
# This just runs `rvm --version` inside the configured $SHELL, which in this case is bash
# -i is interactive -> automatically loads the `~/.bashrc` file since we need the RVM scripts
# to be defined
# -c means command -> runs a single command
/bin/bash -ic rvm --version
```

**Comment by m3c-ode** [comment]
it does not hang actually.
Running this command this way, both in my Linux terminal and VScode terminal (bash) outputs:
```
Warning! PATH is not properly set up, .../.rvm/gems/ruby-3.1.1/bin is not at first place.
         Usually this is caused by shell initialization files. Search for PATH=... entries.
         You can also re-add RVM to your profile by running: rvm get stable --auto-dotfiles
         To fix it temporarily in this shell session run: rvm use ruby-3.1.1
         To ignore this error add rvm_silence_path_mismatch_check_flag=1 to your ~/.rvmrc file.
Ruby enVironment Manager 1.29.12 (latest) (c) 2009-2020 Michal Papis, Piotr Kuczynski, Wayne E. Seguin
```

I have tried looking into it, and changing some PATH in my `.bashrc` and `.profile`, but this message still shows. Not sure how to fix this.
I tried the others suggestions: `rvm get stable --auto-dotfiles` and `rvm use ruby-3.1.1` but still the same.

Just running `rvm -v` in  my Terminal doesn't show the warning.

**Comment by m3c-ode** [comment]
It's very inconsistent so far. sometimes I open a new project and Ruby LSP will run okay, sometimes I still have the `rvm-auto-ruby` command process running crazy. 
I'm really not able to understand the pattern so far.

> 
> The second window is just a regular VS Code window. It defaults to opening with nothing inside, but you can just click open and then select the folder where the Ruby project exists.
> 
> I suspect that something in your shell configs is not happy that we're loading bash without an actual terminal (from NodeJS). You can try removing the `-i` flag from [here](https://github.com/Shopify/vscode-ruby-lsp/blob/d7cb6f1a0256d0bd4dcdd7e42aae4589da16b1a7/src/ruby.ts#L299) and [here](https://github.com/Shopify/vscode-ruby-lsp/blob/d7cb6f1a0256d0bd4dcdd7e42aae4589da16b1a7/src/ruby.ts#L157) to validate this assumption. It will still fail, but if it no longer hangs then it must related to loading the shell configs.

If I modify the code as you suggested, how do I know when opening a new project of VScode window, that the RubyLSP used is going to be the one I cloned? How can I point it in that direction?

**Comment by vinistock** [comment]
You open VS Code on this project (vscode-ruby-lsp), change the code and then when you run F5 the window that opens is running the development version with your changes.

If you change the code again, you can press the reload button to reload the development window.
