### ISSUE TITLE
Shadowenv error

### ISSUE THREAD

**Issue by taichi-ishitani** [Shopify/vscode-ruby-lsp#543]
Hi,

I got `shadowenv error` like screenshot below when booting vscode with the ruby-lsp plugin.

![image](https://user-images.githubusercontent.com/2922232/230402997-1c966e19-6829-48c4-a491-2607e10d0d35.png)

Why this error is reported and how can I resolve it?

vscode version info:

```
バージョン: 1.77.1 (system setup)
コミット: b7886d7461186a5eac768481578c1d7ca80e2d21
 日付: 2023-04-04T23:21:11.906Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No
```

Ruby LSP version: v0.2.3

**Comment by taichi-ishitani** [comment]
Hi @vinistock ,

No. I use `rbenv` to manage Ruby version.
![image](https://user-images.githubusercontent.com/2922232/230406837-3d2023bb-e9d6-4177-87db-b4361b96916c.png)

**Comment by vinistock** [comment]
Do you have the shadowenv extension installed? I think this is not coming from the Ruby LSP but from https://github.com/Shopify/vscode-shadowenv instead.

**Comment by taichi-ishitani** [comment]
Ok, I understood.
I will open an issue on that repository.

Thank you for your quickly response!

**Comment by taichi-ishitani** [comment]
Hi @andyw8 ,
Thank you for your advice. I will try it.

**Comment by taichi-ishitani** [comment]
> @taichi-ishitani shadowenv would be an alternative to rbenv - if you're not using it, then you can just remove that extension.

I removed the shadowenv plugin then this error is not reported.
Thank you for your help!
