### ISSUE TITLE
Server gem is never updated when there is no bundle

### ISSUE THREAD

**Issue by vinistock** [Shopify/vscode-ruby-lsp#547]
When we try to update the server gem in a project without a `Gemfile.lock`, the first time we create `.ruby-lsp/Gemfile.lock`, but then it never gets updated.

We need to change the logic [here](https://github.com/Shopify/vscode-ruby-lsp/blob/e1300a6b313c11230c600e944d40f91a747fd29a/src/client.ts#L450) to update the server automatically. Since projects without a bundle only have the Ruby LSP and debug in the custom Gemfile, I think it should be quick to do this every time.

**Comment by jayanth-kumar-morem** [comment]
Hi @vinistock , I would like to work on this, could you please assign me to this

**Comment by vinistock** [comment]
Awesome! I assigned you to the issue. I think the way to go for this one would be to just remove the `Gemfile.lock` and run bundle install again if there's no top level `Gemfile.lock`. The modified timestamps compare with the top level one, which doesn't exist in this case, so that wouldn't work.

Should just be a matter of checking if
- No top level Gemfile.lock exists
- `.ruby-lsp/Gemfile.lock` exists
- Then remove `.ruby-lsp/Gemfile.lock` and run bundle install

**Comment by jayanth-kumar-morem** [comment]
Hi @vinistock ,

I have raised the PR #561 for resolve this.

I have signed the CLA, but couldn't re-run the CLA job. Could you please re-run the CLA workflow for this pull request? I believe this should resolve the issue.

Thank you for your help!
