### ISSUE TITLE
Allow modifying gem source url

### ISSUE THREAD

**Issue by derek-robinson** [Shopify/vscode-ruby-lsp#558]
Some companies have internal proxy systems for programming libraries for caching, security, etc. I haven't found a way to set the gem source to a different url without it being overwritten. Please let me know if this is more appropriate for the vscode repo or if you need additional information to understand the problem scope

**Comment by vinistock** [comment]
This should be fixed as of `ruby-lsp` v0.7.6. We changed the custom bundle logic version to not specify the source and just use the one defined in the top level `Gemfile` https://github.com/Shopify/ruby-lsp/pull/847.
