### ISSUE TITLE
VSCode extension fails to start ruby-lsp

### ISSUE THREAD

**Issue by adas172002** [Shopify/vscode-ruby-lsp#572]
### Operating System

macOS 12.6.5

### Ruby version

2.7.3

### Project has a bundle

- [X] Has bundle

### Ruby version manager being used

rbenv

### Description

The error message:

> Failed to setup the bundle: bundle install exited with code 6.             See [Troubleshooting](https://github.com/Shopify/vscode-ruby-lsp#troubleshooting) for instructions

Auto detection of ruby version manager works fine. Status window shows **Using Ruby 2.7.3 with rbenv**.

Here's the output of "the last resort" installation command:
```
% BUNDLE_GEMFILE=/Users/adas/Documents/code/bazaRN/ncdb/.ruby-lsp/Gemfile bundle install
Fetching gem metadata from https://rubygems.org/...........
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies....
Bundler could not find compatible versions for gem "language_server-protocol":
  In Gemfile:
    ruby-lsp was resolved to 0.0.1, which depends on
      language_server-protocol

Could not find gem 'language_server-protocol', which is required by gem
'ruby-lsp', in rubygems repository https://rubygems.org/ or installed locally.

Bundler could not find compatible versions for gem "ruby-lsp":
  In Gemfile:
    ruby-lsp
```

**Comment by vinistock** [comment]
I can't really tell why this is happening. Can you see if any of the following fixes it?
- Adding the `ruby-lsp` to your main Gemfile. See if you can successfully bundle install like that or if the problem persists
- Upgrading bundler and rubygems to the latest version

**Comment by adas172002** [comment]
I installed `ruby-lsp` and `language_server-protocol` with `gem install` command. At first everything went well, because bundle check returned *The Gemfile's dependencies are satisfied*.
However, VSCode extension is not starting even now, the only change is error code - now it is
```
ERROR> Your bundle is locked to activesupport (7.0.4.3) from rubygems repository
ERROR> https://rubygems.org/ or installed locally, but that version can no longer be
ERROR> found in that source. That means the author of activesupport (7.0.4.3) has
ERROR> removed it. You'll need to update your bundle to a version other than
ERROR> activesupport (7.0.4.3) that hasn't been removed in order to install.
>> `bundle install` exited with code 7
```
I will look into this later on, perhaps update my bundler & see what gets. Thanks for your support, @vinistock.

**Comment by adas172002** [comment]
> I will look into this later on, perhaps update my bundler & see what gets. Thanks for your support, @vinistock.

Updating bundler to 2.2.34 solved the issue for me.
