### ISSUE TITLE
No errors, but Intellisense not working

### ISSUE THREAD

**Issue by MyApaulogies** [Shopify/vscode-ruby-lsp#589]
### Operating System

Windows / WSL

### Ruby version

3.2.1 and 3.2.2

### Project has a bundle

- [ ] Has bundle

### Ruby version manager being used

asdf

### Description

When I create a new, empty folder and then create a .rb file, Ruby RSP seems to have no errors. However, when I trigger suggestions, nothing comes up other than snippets.

Background info: I just created a Ubuntu WSL followed [these instructions](https://gorails.com/setup/windows/10#final-steps) to install asdf-vm and add the Ruby plugin and Ruby 3.2.2, and now I'm using VS Code and the WSL plugin to create and edit files in it. I verified that `ruby` and `irb` work properly, and I did `gem install ruby-lsp` .

This is the what Output -> Ruby LSP says: 
```
>> Running `bundle install`...
ERROR> [DEPRECATED] This Gemfile does not include an explicit global source. Not using an explicit global source may result in a different lockfile being generated depending on the gems you have installed locally before bundler is run. Instead, define a global source in your Gemfile like this: source "https://rubygems.org".
BUNDLER> Fetching gem metadata from https://rubygems.org/..........
BUNDLER> Resolving dependencies...
BUNDLER> Using bundler 2.4.12
BUNDLER> Using io-console 0.6.0
BUNDLER> Using sorbet-runtime 0.5.10796
BUNDLER> Using language_server-protocol 3.17.0.3
BUNDLER> Using prettier_print 1.2.1
BUNDLER> Using reline 0.3.3
BUNDLER> Using irb 1.6.4
BUNDLER> Using syntax_tree 6.1.1
BUNDLER> Using debug 1.7.2
BUNDLER> Using ruby-lsp 0.4.5
BUNDLER> Bundle complete! 2 Gemfile dependencies, 10 gems now installed.
BUNDLER> Use `bundle info [gemname]` to see where a bundled gem is installed.
>> `bundle install` exited with code 0
Starting Ruby LSP...
Ruby LSP is ready
```

These are my relevant settings: 
```json
"rubyLsp.formatter": "rubocop",
"rubyLsp.yjit": true,
"rubyLsp.rubyVersionManager": "asdf",
"rubyLsp.enabledFeatures": {
    "codeActions": true,
    "diagnostics": true,
    "documentHighlights": true,
    "documentLink": true,
    "documentSymbols": true,
    "foldingRanges": true,
    "formatting": true,
    "hover": true,
    "inlayHint": true,
    "onTypeFormatting": true,
    "selectionRanges": true,
    "semanticHighlighting": true,
    "completion": true,
    "codeLens": true
}
```

This is what my status bar looks like:
![Code_PvWiU20iV8](https://user-images.githubusercontent.com/49665239/235264287-aed3f00b-eb2d-4b54-8ce9-9d155292cf73.png)

**Comment by vinistock** [comment]
The Ruby LSP doesn't support go to definition or autocomplete yet. We're still working on it.

You can check supported features [here](https://shopify.github.io/ruby-lsp/RubyLsp/Requests.html).

**Comment by 99linesofcode** [comment]
@vinistock is this being worked on somewhere in the open? I'd love to be able to track progress towards a (experimental) release. Thanks

**Comment by AlvesJorge** [comment]
So glad I found this issue thread.
I thought this extension was meant to have intellisense, specially since the deprecated [vscode-ruby](https://github.com/rubyide/vscode-ruby) points to this one extension as its defacto successor.
I'm guessing I'm not the only one that gets here through the suggestion of the other extension, so it might be worth it to mention that this feature is not supported.

@vinistock if I may ask, what extension do you then use for ruby intellisense?

**Comment by AlvesJorge** [comment]
@99linesofcode I quickly reached the same conclusion, it seems solargraph is the only ruby intellisense for vscode and it seems to work without much hassle. Unfortunately the documentation on how to use it is outdated.  
Did you have any luck getting intellisense for Rails? I've seen there's a "plugin" but I can't seem to get it to work.
