### ISSUE TITLE
seems .bundle/config is ignored

### ISSUE THREAD

**Issue by tomocrafter** [Shopify/vscode-ruby-lsp#597]
### Operating System

Ubuntu 23.04

### Ruby version

3.0.6

### Project has a bundle

- [X] Has bundle

### Ruby version manager being used

other (please specify in description)

### Description

version manager: rtx (`1.29.6 linux-x64 (4cc6478 2023-05-07)`)

My gemfile in the project includes private gem which requires credentials so I stored credentials and `BUNDLE_PATH` to `.bundle/config` in project root.
but opening vscode occurs `bundle install` error following:
```
>> Running `bundle install`...
ERROR> Authentication is required for rubygems.xxx.xxx.
ERROR> Please supply credentials for this source. You can do this by running:
ERROR> `bundle config set --global rubygems.xxx.xxx username:password`
ERROR> or by storing the credentials in the `BUNDLE_RUBYGEMS__XXX__XXX`
ERROR> environment variable
>> `bundle install` exited with code 17
```

hope it reads `.bundle/config` or add custom `bundle install` command option to extension so I can set local environment for bundle

Thank you.

**Comment by andyw8** [comment]
Hi @tomocrafter,

One way around this might be to store those credentials at the global level, e.g. in `~/.bundle.config`, which should be picked up by ruby-lsp. Does that help you?

**Comment by vinistock** [comment]
The extension just executes `bundle install` in a shell. The bundler process should pick up `~/.bundle/config` normally.

Does executing the command manually work?
```shell
BUNDLE_GEMFILE=/path/to/your/project/.ruby-lsp/Gemfile bundle install
```

**Comment by andyw8** [comment]
@tomocrafter I'll close this for now, feel free to re-open if you need further support.

**Comment by andyw8** [comment]
(if we [switch](https://github.com/Shopify/vscode-ruby-lsp/issues/550) to using `bundle-compose` it may prevent this from being an issue).

**Comment by vinistock** [comment]
This PR should fix the problem https://github.com/Shopify/ruby-lsp/pull/1093. We were pointing to the wrong bundle app config path because we set `BUNDLE_GEMFILE` and it defaults to a relative path from that.

**Comment by tomocrafter** [comment]
@vinistock Thank you for all kind support!
now I'm wating for release of ruby-lsp gem v 0.12.0 to confirm it fixed. I'll update this post
