### ISSUE TITLE
Why my "Using Formatter: none" ?

### ISSUE THREAD

**Issue by Lyriraki** [Shopify/vscode-ruby-lsp#598]
### Operating System

Mac OS

### Ruby version

3.2.2

### Project has a bundle

- [ ] Has bundle

### Ruby version manager being used

asdf

### Description

I installed rubocop with the command 'gem install rubocop', but when I opened my rails project, and opened ruby-lsp I found that my formatter says "Using Formatter: none"

**Comment by andyw8** [comment]
@Lyriraki other tools may take a different approach, but the problem with not having RuboCop in the Gemfile is that you can't guarantee which version is available, so other developers on a project may get different results when formatting.

**Comment by Lyriraki** [comment]
> @Lyriraki other tools may take a different approach, but the problem with not having RuboCop in the Gemfile is that you can't guarantee which version is available, so other developers on a project may get different results when formatting.

Thank you, your information helped me a lot
