### ISSUE TITLE
Tests not running despite everything being setup correctly.

### ISSUE THREAD

**Issue by krainboltgreene** [Shopify/vscode-ruby-lsp#762]
### Operating System

macOS 13.2.1 (22D68)

### Ruby version

ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin22]

### Project has a bundle

- [X] Has bundle

### Ruby version manager being used

asdf

### Description

My test explorer UI shows no tests, the `Run test in terminal` just opens an empty terminal, the Debug current test just opens a modal that says `Debugger exited with status 1` with no logs or helpful information.

I have `ruby-lsp` and `ruby-lsp-rails` installed, but I'm not sure I needed to? The trace shows nothing valuable. It seems like it's running correctly.

**Comment by vinistock** [comment]
We only support Minitest / test-unit out of the box. To add RSpec support, it would require creating a [Ruby LSP server extension](https://github.com/Shopify/ruby-lsp/blob/main/SERVER_EXTENSIONS.md) that knows how to understand RSpec DSLs.

However, it's funny to me that you're still seeing the code lens buttons to run in the terminal or debug. We only add those to methods like `def test_something` or test classes `MyTest`, neither of which are used in RSpec tests.

Where are you seeing the code lenses?

**Comment by krainboltgreene** [comment]
Woof, that's a sizable chunk of work. I can understand now why it's not supported already.

> Where are you seeing the code lenses?

So this was only really visible when I had another code lenses set up for rspec specifically, because Test Explorer UI showed *two* "sections", one was empty and one was the rspec tests recognized by the other extension.
