### ISSUE TITLE
Installation of gem ruby-lsp fails

### ISSUE THREAD

**Issue by ThomasOwens** [Shopify/vscode-ruby-lsp#790]
### Operating System

Windows / devcontainer

### Ruby version

3.2

### Project has a bundle

- [ ] Has bundle

### Ruby version manager being used

rvm

### Description

I created a new Ruby on Rails & Postgres Dev Container using VS Code, connected to it, and am attempting to start a new project.

After connecting to the devcontainer, the following error appears:

Failed to setup the bundle: Command failed: gem install ruby-lsp ERROR: While executing gem ... (Gem::FilePermissionError) You don't have write permissions for the /usr/local/rvm/gems/default directory. /usr/local/lib/ruby/3.2.0/rubygems/installer.rb:712:in `verify_gem_home' /usr/local/lib/ruby/3.2.0/rubygems/installer.rb:902:in `pre_install_checks' /usr/local/lib/ruby/3.2.0/rubygems/installer.rb:302:in `install' /usr/local/lib/ruby/3.2.0/rubygems/resolver/specification.rb:104:in `install' /usr/local/lib/ruby/3.2.0/rubygems/request_set.rb:194:in `block in install' /usr/local/lib/ruby/3.2.0/rubygems/request_set.rb:182:in `each' /usr/local/lib/ruby/3.2.0/rubygems/request_set.rb:182:in `install' /usr/local/lib/ruby/3.2.0/rubygems/commands/install_command.rb:214:in `install_gem' /usr/local/lib/ruby/3.2.0/rubygems/commands/install_command.rb:230:in `block in install_gems' /usr/local/lib/ruby/3.2.0/rubygems/commands/install_command.rb:223:in `each' /usr/local/lib/ruby/3.2.0/r...

I was under the impression that this was related to #536, #664, #789, #750 or one of the related linked issues/PRs. However, both VS Code and the Ruby LSP plugin are fully updated and this problem persists even though these issues have been marked as resolved. It's not clear if there's a regression or this is a different issue.

Since this plugin is installed out-of-the-box in the Ruby on Rails & Postgres devcontainer, I would not expect errors when creating and connecting to this devcontainer.

**Comment by andyw8** [comment]
Is it this devcontainer repo? https://github.com/luizkowalski/devcontainer-rails/

**Comment by ThomasOwens** [comment]
@andyw8 No. I'm using https://github.com/devcontainers/templates/tree/main/src/ruby-rails-postgres.

I use this directly through VS Code. I create a new workspace, open the command palate, and use Dev Containers: Add Dev Container Configuration Files. I select the "Ruby on Rails & Postgres" configuration files, which are maintained by devcontainers.

There are other options. There is a Ruby option also maintained by devcontainers along with a Ruby on Rails that is community maintained. I can experiment with these to see if they also have the issue. I don't know if this plugin is included out-of-the-box in the other configuration files, though.

I wonder if this is partially related to https://github.com/devcontainers/templates/issues/188. However, even setting the `BUNDLE_APP_CONFIG` and `BUNDLE_PATH` values in `devcontainer.json` still results in the same error.

**Comment by andyw8** [comment]
You said it's "installed out-of-the-box in the Ruby on Rails & Postgres devcontainer" but  I can't see any reference to Ruby LSP in there. 🤔

**Comment by vinistock** [comment]
The thing that is triggering `gem install` is definitely us. We need to install the `ruby-lsp` gem in order to launch the language server.

And it seems that the devcontainer only has the default RVM gemset, which doesn't give you permissions to install there.

Are there not other gemsets in the container? How do people run `bundle install` or `gem install` in the container?

I think it's worth understanding if the container should be coming with a user owned gemset.

**Comment by vinistock** [comment]
I'm trying to understand the differences between a developer installing gems regularly (using `bundle install`) vs what we're doing.

So you always have `BUNDLE_PATH` pointing to `vendor/bundle` in the container?

That might be the reason, in which case we'll need to think about how we can improve this in the LSP. To avoid forcing people to add the `ruby-lsp` gem to their Gemfiles, we install it globally using `gem install ruby-lsp`.

But if the only place you have permissions to install gems is under `vendor/bundle`, that won't work. I'm not sure if `gem install` allows you to select a path. Maybe we could take `BUNDLE_PATH` into consideration and point it there?

**Comment by ThomasOwens** [comment]
I made the changes to the Ruby on Rails & Postgres devcontainer, which resolved this issue. The changes have been merged into the devcontainer repository.

**Comment by andyw8** [comment]
https://github.com/devcontainers/templates/pull/202

Thank you @ThomasOwens!
