### ISSUE TITLE
Modules::include wrong indentation

### ISSUE THREAD

**Issue by akirataguchi115** [Shopify/vscode-ruby-lsp#828]
### Ruby version

ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]

### Code snippet
```ruby
class Brewery < ApplicationRecord
  include RatingAverage
  has_many :beers, dependent: :destroy
end
```
### Description

Paste the code snippet. Remove line 2. Start writing the same line starting with "include" with indentation already input there like in the snippet.

### Expected output

The indentation holds and the include gets typed correctly there.

### Actual output
Ruby LSP indents the "include" backwards as if the include shouldn't be indented.

According to the Official Ruby API `include` should be indented: https://docs.ruby-lang.org/en/master/Module.html

**Comment by davidcelis** [comment]
Not sure if its the _same_ issue or only related, but I've found some other auto indentation issues when using Shopify's Ruby LSP extension. In addition to the original problem around `include` being auto-indented as soon as you type `in` (probably because it tries to detect it as the pattern matching keyword), I've also noticed inconsistent behavior with `do...end` blocks. For example, in RSpec tests, different things happen with different kinds of blocks:

```ruby
describe "an rspec test group" do
# does not properly increase indentation after entering the newline

let(:variable) do
  # properly increases indentation after entering the newline
```

**Comment by akirataguchi115** [comment]
I'll try to reproduce this in the next 48 hours.

**Comment by akirataguchi115** [comment]
I am able to reproduce the bug. Editing the Code snippet to be more readable as the issue template messed it up.

I can confirm that the wrong auto indent already happens, as stated above, when typing "in".

I can also reproduce the following bug mentioned above:
```ruby
describe "an rspec test group" do
# does not properly increase indentation after entering the newline

let(:variable) do
  # properly increases indentation after entering the newline
```

The bug still happens after setting the recommended configurations and disabling `ruby-rubocop` extension.

**Comment by akirataguchi115** [comment]
Great to know that you can reproduce it. I'm not using Copilot though.

**Comment by davidcelis** [comment]
Will that fix the issue in VSCode? It seems like that's against the now-deprecated default Ruby extension, and everybody now is being told to install Shopify's Ruby LSP extension

**Comment by andyw8** [comment]
The change above corresponds to the built-in Ruby Language Basics extension:

<img width="629" alt="Screenshot 2024-01-17 at 2 20 40 PM" src="https://github.com/Shopify/vscode-ruby-lsp/assets/13400/d4304e75-3fd0-480b-b2a9-1fafce530cad">

The extension that was deprecated was https://github.com/rubyide/vscode-ruby
