### ISSUE TITLE
Add a documentation section explaining the custom bundle

### ISSUE THREAD

**Issue by vinistock** [Shopify/vscode-ruby-lsp#869]
The custom bundle is sometimes a source of confusion. Users don't always realize why it's necessary or how it is supposed to work.

The fact that we hide the `.ruby-lsp` directory automatically in VS Code, makes it even more obscure if something is not working right.

Let's add a new README section explaining what the custom bundle is and how it works. And let's mention that the extension automatically hides the directory.

**Comment by GrantBirki** [comment]
> The custom bundle is sometimes a source of confusion

I am currently in the "confused realm". I am trying to use `ruby-lsp` in a project with a bundle. The bundle contains Gems that are in an internal GitHub RubyGems package registry. Additionally, I have Gems that are vendored in my project's `vendor/cache` directory. The `ruby-lsp` server is just continuously crashing and I'm not certain how to alter my project's custom bundle to resolve the issue.
