### ISSUE TITLE
Failed to activate none environment: Command failed: ruby -rjson -e ... compile error (SyntaxError)

### ISSUE THREAD

**Issue by PaulScorthorne** [Shopify/vscode-ruby-lsp#891]
### Operating System

Windows 10

### Ruby version

3.2.2

### Project has a bundle

- [X] Has bundle

### Ruby version manager being used

no manager

### Description

I have been running Ruby LSP in VS Code for a short while (after the deprecation of the previous Ruby extension), but when I came back to it this morning upon opening my first .rb file I was greeted with:

> Failed to activate none environment: Command failed: ruby -rjson -e "STDERR.printf(%{RUBY_ENV_ACTIVATE%sRUBY_ENV_ACTIVATE}, JSON.dump({ env: ENV.to_h, ruby_version: RUBY_VERSION, yjit: defined?(RubyVM::YJIT) }))" -e:1: syntax error, unexpected end-of-input, expecting ')' ...V_ACTIVATE%sRUBY_ENV_ACTIVATE}, ... ^ -e: compile error (SyntaxError)

I've run through all the steps on https://github.com/Shopify/vscode-ruby-lsp#troubleshooting without success. 

I also noted https://github.com/Shopify/vscode-ruby-lsp/issues/883, but my Path does not contain any spaces. It is simply `C:\Ruby32-x64\bin`

Running `ruby -rjson -e "STDERR.printf(%{RUBY_ENV_ACTIVATE%sRUBY_ENV_ACTIVATE}, JSON.dump({ env: ENV.to_h, ruby_version: RUBY_VERSION, yjit: defined?(RubyVM::YJIT) }))"` in a terminal returns the JSON block it appears to be after quite happily, including the appropriate `"ruby_version":"3.2.2"`

The rest of my system knows where Ruby is, what version it is, installs and runs gems, etc. I am fundamentally stumped on what the issue is or where it might have come from.

I have the latest version of the ruby-lsp gem installed, 0.21.3, and the above is the same on the VSCode Release 0.4.17 and Pre-Release 0.5.0 versions.

I also attempted to define a custom activation as suggested in that ticket anyway, following the instructions at https://github.com/Shopify/vscode-ruby-lsp/blob/main/VERSION_MANAGERS.md#custom-activation, but that just led to a different error:

> Failed to activate custom environment: Command failed: PATH=C:\Ruby32-x64\bin:$PATH && ruby -rjson -e "STDERR.printf(%{RUBY_ENV_ACTIVATE%sRUBY_ENV_ACTIVATE}, JSON.dump({ env: ENV.to_h, ruby_version: RUBY_VERSION, yjit: defined?(RubyVM::YJIT) }))" 'ruby' is not recognized as an internal or external command, operable program or batch file.

I tried every variation of "C:\Ruby32-x64\bin" I could think of (double slashed, reverse slashed, trailing slashes, relative paths, etc) all to the same result.

Happy to provide any additional info or try other potential troubleshooting steps.

**Comment by vinistock** [comment]
Thank you for the bug report! I suspect that the extension is not finding the right Ruby version. Since you have no version manager, you'll indeed need to use the custom activation to insert the path to Ruby in the `PATH`.

That said, this configuration `PATH=C:\Ruby32-x64\bin:$PATH` looks like Unix, which I don't believe will work on Windows.

I have no experience using Windows, but based on [this StackOverlow answer](https://stackoverflow.com/questions/9546324/adding-a-directory-to-the-path-environment-variable-in-windows) it seems that you need to use `set`, wrap the current `PATH` in `%` and use `;` as a separator.

**Comment by melt-adzuki** [comment]
I leave this comment just to express that I have the same error. I use Ruby 3.2.2 installed via RubyInstaller2 on Windows 11 (no extra managers installed), getting the same error:

```
Failed to activate none environment: Command failed: ruby -rjson -e "STDERR.printf(%{RUBY_ENV_ACTIVATE%sRUBY_ENV_ACTIVATE}, JSON.dump({ env: ENV.to_h, ruby_version: RUBY_VERSION, yjit: defined?(RubyVM::YJIT) }))" -e:1: syntax error, unexpected end-of-input, expecting ')' ...V_ACTIVATE%sRUBY_ENV_ACTIVATE}, ... ^ -e: compile error (SyntaxError)
```

Did recent update or something like that make this error appear?

**Comment by vinistock** [comment]
Folks, thank you so much for debugging and pointing us to the right direction. The changes in https://github.com/Shopify/vscode-ruby-lsp/pull/904 should fix the issue 🙏.
