### ISSUE TITLE
Go to definition not working with custom Gemfile 

### ISSUE THREAD

**Issue by backpackerhh** [Shopify/vscode-ruby-lsp#900]
### Operating System

Ubuntu MATE 22.04

### Ruby version

3.2.2

### Project has a bundle

- [X] Has bundle

### Ruby version manager being used

rvm

### Description

Some notes:

* The custom Gemfile is successfully recognized, unlike #849
* The project is running in Docker.
* I've created an RVM gemset (named ruby-lsp) where all gems are installed.
* The directory `.ruby-lsp` does not exist in my working directory. Maybe is the [expected behavior](https://github.com/Shopify/vscode-ruby-lsp/blob/ee112d791073d91e5fd5ddd91c45c46b1688b5ae/src/client.ts#L466)?
* RuboCop offenses are properly highlighted.
* _Go to definition_ does not work most of the time.

And that last point is the one that I'm trying to solve or at least understand how to benefit from that feature.

### VSCodium version

1.84.2

### VSCodium extension version

0.4.13

### VSCodium settings

```json
{
  "[ruby]": {
        "editor.defaultFormatter": "Shopify.ruby-lsp",
        "editor.formatOnSave": false,
        "editor.formatOnType": false,
        "editor.tabSize": 2,
        "editor.insertSpaces": true,
        "editor.semanticHighlighting.enabled": true,
    },
    "rubyLsp.rubyVersionManager": "rvm",
    "rubyLsp.formatter": "rubocop",
    "rubyLsp.enableExperimentalFeatures": true,
    "rubyLsp.bundleGemfile": "<absolute/path>/ruby-lsp/Gemfile",
    "rubyLsp.enabledFeatures": {
        "codeActions": true,
        "diagnostics": true,
        "documentHighlights": true,
        "documentLink": true,
        "documentSymbols": true,
        "foldingRanges": true,
        "formatting": false,
        "hover": true,
        "inlayHint": true,
        "onTypeFormatting": false,
        "selectionRanges": true,
        "semanticHighlighting": true,
        "completion": true,
        "codeLens": true,
        "definition": true,
        "workspaceSymbol": true,
        "references": true
    },
    "rubyLsp.yjit": true,
}
```

### ruby-lsp gem version

0.12.3

### Custom Gemfile content

```
# frozen_string_literal: true

source "https://rubygems.org"

gem "ruby-lsp"
gem "rubocop", "~> 1.57"
gem "rubocop-performance"
gem "rubocop-rspec"

gem "hanami", "~> 2.0"
gem "hanami-controller", "~> 2.0"
gem "hanami-router", "~> 2.0"
gem "hanami-validations", "~> 2.0"
gem "hanami-reloader"
gem "hanami-rspec"

gem "rom", "~> 5.3"
gem "rom-sql", "~> 3.6"

gem "dry-types", "~> 1.0", ">= 1.6.1"
```

### Ruby LSP output in VSCodium

```
Ruby LSP> Trying to activate Ruby environment with command: /usr/bin/zsh -ic 'rvm-auto-ruby -rjson -e "printf(%{RUBY_ENV_ACTIVATE%sRUBY_ENV_ACTIVATE}, JSON.dump(ENV.to_h))"' inside directory: /media/david/Documents/Projects/ruby-lsp
Starting Ruby LSP v0.12.3...
Ruby LSP is ready
```

### Project's Gemfile

![Screenshot at 2023-11-17 13-36-09](https://github.com/Shopify/vscode-ruby-lsp/assets/685978/05bceb97-1fe6-4eb8-9510-bfc0f2918765)

Only some gems present in the custom Gemfile seems to be recorgnized. For instance, only `hanami-rspec` from all Hanami-related gems used in the project.

**Comment by backpackerhh** [comment]
> Thank you for the report. When say, "doesn't work most of the time", are you talking about go to definition for methods?
> 
> We haven't finished adding support for methods yet ([Shopify/ruby-lsp#899](https://github.com/Shopify/ruby-lsp/issues/899)). However, it should be working properly for classes, modules and constants. Are you able to go to definition on those?
> 
> Also, you can always find details about our supported features in the [documentation](https://shopify.github.io/ruby-lsp/RubyLsp/Requests.html).

Thanks for your answer, @vinistock.

Yes, I was mostly talking about go to definition for methods, although I've found some unexpected behavior (for me, of course) with some classes/modules. I need to check it again so I can provide with some examples.

Anyway, I've checked the list of supported features included in the documentation link you provided and I can confirm that completion doesn't work for me with code such as the one in the image (obviously requiring classes from my project):

![https://shopify.github.io/ruby-lsp/completion.gif](https://shopify.github.io/ruby-lsp/completion.gif)

Additionally, I'd like to confirm some details:

* Should native Ruby classes and modules be working right now? I guess those parts of the code written in C won't work, but what about the ones written in Ruby?
* Why `.ruby-lsp` directory is not present in my project folder?

**Comment by vinistock** [comment]
Oh, you mean the require path completion not the constant completion. Yeah, we noticed it stopped working suddenly and submitted a report to the [LSP VS Code package](https://github.com/microsoft/vscode-languageserver-node/issues/1342).

It might be a bug in VS Code itself given that we're returning proper completion items and it just never shows the selection to the user. Still trying to figure that one out.
