### ISSUE TITLE
LSP not working in vs code

### ISSUE THREAD

**Issue by keenfoong** [Shopify/vscode-ruby-lsp#926]
### Operating System

Windows Home 10

### Ruby version

ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x64-mingw-ucrt]

### Project has a bundle

- [ ] Has bundle

### Ruby version manager being used

no manager

### Description

I just installed with RubyInstaller 3.2.2. It doesn't do anything at all, no error, no autocomplete to jump to anything.

**Comment by keenfoong** [comment]
Ah I'm just using vanilla ruby, I assumed this was for the vanilla ruby since rails is not mentioned at all on the front page.

There is nothing on the output tab: 
![Code_L4rvYH0odc](https://github.com/Shopify/vscode-ruby-lsp/assets/31301148/596e6e3c-b63b-42f2-8f9f-85af745a4b7f)

**Comment by LyleDavis** [comment]
I also think I'm seeing this issue now. It's very strange, there are no logs in the output channel indicating it has failed to start. I'm on a macOS host but this is running within a devcontainer on ruby 3.2.

I'm happy to help debugging but not sure what info is needed for it as there don't seem to be any logs surfaced in the output channel within vs code itself. 

Interestingly, it doesn't matter what I seem to do but the extension always gets stuck in this state and there are no logs either in the output window in VS code or the log file that that points at. That happens even when stopping ruby-lsp, it stays in the `Ruby LSP: Starting` state in the vs code window itself.

**Comment by parkernilson** [comment]
I am also trying to run the Ruby LSP extension on VSCode on MacOS. I am using rbenv as manager with global version set to 3.2.2. The plugin doesn't do anything and I can't even get it to output anything in the vscode output tab! I launch vscode using the `code .` command.

**Comment by parkernilson** [comment]
@LyleDavis I am new to Ruby, do you think you could point me to some resource that will help me know how to set up my project correctly so that it will work with the Ruby LSP?

**Comment by calmacleod** [comment]
Seeing the same problem - working as expected on 0.4.22 and breaks on 0.5.3 Rolling back works for the time being. Using a custom Gemfile pointing to a separate directory with only the ruby-lsp gem installed. Project is also configured as a monorepo so I suspect that's part of the problem.

**Comment by vinistock** [comment]
> Project is also configured as a monorepo so I suspect that's part of the problem.

We recently implemented support for multi-root workspaces. It was actually not following VS Code guidelines before. Here's the [documentation](https://github.com/Shopify/vscode-ruby-lsp?tab=readme-ov-file#multi-root-workspaces) on how it works.

**Comment by Bo98** [comment]
> we already have a [custom Gemfile option](https://github.com/Shopify/vscode-ruby-lsp?tab=readme-ov-file#using-a-custom-gemfile)

Looks like it doesn't work in 0.5.x as it's hardwired to abort if there's no lockfile in the workspace root: https://github.com/Shopify/vscode-ruby-lsp/blob/v0.5.4/src/rubyLsp.ts#L114-L122

2611f461f6b09b3056cb2fc1ee730d92a237f877 looks to maybe fix it (though ideally shouldn't need to prompt if custom Gemfiles are set)

**Comment by rwojnarowski** [comment]
I'm also having same issue and can confirm that it doesn't work in monorepo. 

For example:
```
/monorepo/.ruby_version
/monorepo/backend/.ruby_version
/monorepo/backend/Gemfile
/monorepo/frontend/
```
If i open vscode in monorepo root directory (`code ./monorepo`) it doesn't work although i do have there .ruby-version file for rbenv.

If i open vs code in /backend directory (`code ./monorepo/backend`) it does work.

Logs looks good for both cases:
```
[info] Ruby LSP> Running bundle install for the custom bundle. This may take a while...
Ruby LSP> Command: (bundle check || bundle install) 1>&2
[info] The Gemfile's dependencies are satisfied
[info] Starting Ruby LSP v0.13.2...
[info] Ruby LSP is ready
```

**Comment by vinistock** [comment]
This issue ended up being overloaded with multiple different problems, so it's hard to tell what has already been fixed.

Version [v0.5.5](https://github.com/Shopify/vscode-ruby-lsp/releases/tag/v0.5.5) came out fixing a launch issue for multi-root workspaces that was affecting monorepos.

Please give the latest extension a try and, if it doesn't work, open a separate issue with more details so that we can narrow down the bug and fix it.
