### ISSUE TITLE
Debugging requires a workspace folder to be opened

### ISSUE THREAD

**Issue by alexyao2015** [Shopify/vscode-ruby-lsp#947]
### Operating System

Mac + Remote linux server over SSH 

### Ruby version

2.7.8

### Project has a bundle

- [ ] Has bundle

### Ruby version manager being used

no manager

### Description

I am running on a remote linux machine over SSH using a code workspace file. 

The file is in my user home directory with the following contents.

```
  "folders": [
    {
      "path": "/home/myuser"
    }
  ]
```

My debug configuration is as follows:

```
        {
          "name": "Debug test",
          "type": "ruby_lsp",
          "request": "launch",
          "program": "ruby /home/myuser/.../test.rb",
        },
```

The script open in my editor. When clicking debug, I receive an error message `Debugging requires a workspace folder to be opened` no matter what. The folder is open in my workspace. Even if I set the folder to open the exact folder where test.rb is placed, I still receive the same message. I'm not sure if this is caused because this is a remote development environment or something wrong with my configuration.

**Comment by wolfymaster** [comment]
Same issue. I've spent over 5 hours trying to fix this. This makes me hate vscode even more. At this point, I just clone the repo and do it Rubymine which works 100% of the time.

**Comment by vinistock** [comment]
Thank you for the bug report. I think there might be a few issues at play here.

1. Is your VS Code configured to connect with the SSH machine? We have some [docs](https://github.com/Shopify/vscode-ruby-lsp/blob/main/TROUBLESHOOTING.md#developing-on-containers) about that setup. For what is worth, we use that same setup so it should be working fine
2. The second point is the Ruby version. We only support Ruby 3.0 and above, but there are possible workarounds. We also have [docs](https://github.com/Shopify/vscode-ruby-lsp?tab=readme-ov-file#ruby-version-requirement) for those

**Comment by alexyao2015** [comment]
I ran another test to eliminate all variables. I simply created a new directory locally on my macbook and created a single file within this directory called `test.rb` with a single line contained `puts "hello world"`. I installed ruby 3.2.2 and placed it in the path, confirming the version with `ruby -v`. Next I opened the directory in vscode and installed the extension. Upon clicking `Run and Debug`, then selecting `Ruby LSP debug client`, I received the same dreaded message  `Debugging requires a workspace folder to be opened`.

**Comment by scheals** [comment]
@alexyao2015 

Do you have the `.ruby-lsp` directory in your project's root? `ls -a` should show it. I have a feeling it is not there. Create a dummy `Gemfile.lock` file in project root, it doesn't have to have anything to do with a normal `Gemfile.lock` file - you can write your favourite poem if you'd like. Afterwards, close VSCode and open it once again. Ruby-LSP most likely will start, due to it creating `.ruby-lsp` directory now.

**Comment by alexyao2015** [comment]
@scheals 

That was it! Just creating the `Gemfile.lock` at the root of the workspace seemed to have immediately activated the extension's features and debugging was successful. Presumably this is a bug since it appears that the extension should be [activated automatically](https://github.com/Shopify/vscode-ruby-lsp/blob/2611f461f6b09b3056cb2fc1ee730d92a237f877/src/rubyLsp.ts#L118) when a Ruby file is opened in the editor?

**Comment by sometimescasey** [comment]
@scheals thanks so much, I ran into the same "Debugging requires a workspace folder to be opened" error. Ruby 3.2.2. Adding the `Gemfile.lock` at the project root and restarting VSCode resulted in successful debugging.

@alexyao2015 - it looks like the [change that you linked to](https://github.com/Shopify/vscode-ruby-lsp/pull/945/files) was added 2 weeks ago, and the extension is still on `v0.5.4`, so I"m guessing that fix hasn't been released yet:

<img width="265" alt="image" src="https://github.com/Shopify/vscode-ruby-lsp/assets/16248601/ba472a4a-238e-4a22-af1d-bbafd49f6539">

<img width="169" alt="image" src="https://github.com/Shopify/vscode-ruby-lsp/assets/16248601/8455b2aa-203b-4e73-bba6-597a2b65bc45">

**Comment by vinistock** [comment]
@oriolgual and did you already configure your multi-root workspace through the [docs](https://github.com/Shopify/vscode-ruby-lsp?tab=readme-ov-file#multi-root-workspaces)?

**Comment by oriolgual** [comment]
Yup. Actually, downgrading to 0.5.4 fixes the error for me.

**Comment by pablox70** [comment]
I'm having the exact same issue/error running in a container and it was working before the upgrade.  Downgrading to 0.5.4 also fixed the issue for me.

**Comment by vinistock** [comment]
@oriolgual and @pablox70, can you please answer these questions to help me diagnose what's happening?

- How are you launching the debugger? Are you using your `launch.json` configurations through the run and debug panel or are you using the `debug` code lens buttons that appear on top of tests?
- If you have a monorepo, where do you put your `launch.json` configuration file? Is it in the top level or inside the sub directories?
