### ISSUE TITLE
Changelog on VSCode Marketplace include pre-release versions

### ISSUE THREAD

**Issue by renchap** [Shopify/vscode-ruby-lsp#996]
### Operating System

macOS

### Ruby version

3.2.3

### Project has a bundle

- [ ] Has bundle

### Ruby version manager being used

asdf

### Description

The changelog shown in the extension detail page in VSCode contains the pre-release versions.

For example here, 0.6 versions are noted as pre-releases on Github, but they are shown in the changelog for 0.5.8.

<img width="899" alt="image" src="https://github.com/Shopify/vscode-ruby-lsp/assets/42070/aeca69c2-021d-48a3-aaaa-36965a939268">

The Github action that generates the changelog should probably be modified to not include pre-releases (if building a stable version), and maybe also to sort the versions by name rather than by release date?

**Comment by andyw8** [comment]
Thank you for the report, we'll look into fixing this.

**Comment by snutij** [comment]
Hello @andyw8, we could add a filter here: 

https://github.com/Shopify/vscode-ruby-lsp/blob/92d0d621de7cd0affd712b926e752ce0039a4a9a/.github/workflows/publish.yml#L36-L38

Following [API documentation](https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#list-releases), there is a field `prerelease`.

To get something like

```javascript
const changelog = releases
              .filter((release) => !release.prerelease)
              .map((release) => `# ${release.tag_name}\n${release.body}\n`)
              .join("\n");
```

I can handle it, if you are agree with that.

**Comment by andyw8** [comment]
@snutij Sounds good, thank you!
